import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/header/Header";
const fontDiner = localFont({
  src: "./fonts/FontdinerSwanky-Regular.ttf",
  variable: "--font-diner",
  style: "normal",
});
const EduFont = {
  src: [
    {
      Path: "./fonts/EduAUVICWANTArrows-Bold.ttf",
      weight: "bold",
      style:"normal",
    },
    {
      Path: "./fonts/EduAUVICWANTArrows-Medium.ttf",
      weight: "500",
      style:"normal",
    },
    {
      Path: "./fonts/EduAUVICWANTArrows-SemiBold.ttf",
      weight: "700",
      style:"normal",
    },
   
  ],
  variable:"--font-edu"
}
const playFair = localFont({
  src: [
    {
      path: "./fonts/PlayfairDisplay-ExtraBold.ttf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--play-fair",
});
  


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${EduFont.variable} ${playFair.variable} `}>
        <Header />
        {children}
      </body>
    </html>
  );
}
